### ISSUE TITLE
Спам сообщениями из-за ошибки Bad Request

### ISSUE THREAD

**Issue by b1oki** [alexandersobyanin/python.alexandersobyanin.ru#5]
```python
Traceback (most recent call last):
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/b1oki/mysite/flask_app.py", line 43, in telegram_sret_shot_bot_webhook
    return telegram.handle_sret_shot_bot(request.get_json())
  File "/home/b1oki/mysite/telegram.py", line 50, in handle_sret_shot_bot
    return basic_message_handler(update, telegram_sret_shot_bot, 'Скоро сможете прислать скриншот…')
  File "/home/b1oki/mysite/telegram.py", line 81, in basic_message_handler
    bot.forwardMessage(telegram_admin_chat_id, chat_id, update['message']['message_id'])
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/telepot/__init__.py", line 519, in forwardMessage
    return self._api_request('forwardMessage', _rectify(p))
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/b1oki/.virtualenvs/python-env/lib/python3.7/site-packages/telepot/api.py", line 150, in _parse
    raise exception.TelegramError(description, error_code, data)
telepot.exception.TelegramError: ("Bad Request: the message can't be forwarded", 400, {'ok': False, 'error_code': 400, 'description': "Bad Request: the message can't be forwarded"})
```

**Comment by b1oki** [comment]
update content:

```json
{"update_id": 123, "message": {"message_id": 2, "from": {"id": 123, "is_bot": true, "first_name": "Group", "username": "GroupAnonymousBot"}, "sender_chat": {"id": -123, "title": "СретШот Chat", "type": "supergroup"}, "chat": {"id": -123, "title": "СретШот Chat", "type": "supergroup"}, "date": 123, "new_chat_participant": {"id": 123, "is_bot": true, "first_name": "sretshotbot", "username": "SretShotBot"}, "new_chat_member": {"id": 123, "is_bot": true, "first_name": "sretshotbot", "username": "SretShotBot"}, "new_chat_members": [{"id": 123, "is_bot": true, "first_name": "sretshotbot", "username": "SretShotBot"}]}}
```
