### ISSUE TITLE
Зацикливается уведомление от пользователя, заблокировавшего бота

### ISSUE THREAD

**Issue by b1oki** [alexandersobyanin/python.alexandersobyanin.ru#8]
```
2024-02-05 02:43:20,941: Exception on /telegram/TELEGRAM_BOT_EUC_URALS_PETS_BOT/7***-****-****-****-***5cc1 [POST]
Traceback (most recent call last):
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/b1oki/mysite/flask_app.py", line 38, in telegram_euc_urals_pets_bot_webhook
    return telegram.handle__euc_urals_pets_bot(request.get_json())
  File "/home/b1oki/mysite/telegram.py", line 46, in handle__euc_urals_pets_bot
    return basic_message_handler(update, telegram_euc_urals_pets_bot, 'Привет, монокотята! Скоро бот заработает…')
  File "/home/b1oki/mysite/telegram.py", line 85, in basic_message_handler
    bot.sendMessage(chat_id, ''.join(answer))
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/telepot/__init__.py", line 513, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/telepot/api.py", line 155, in request
    return _parse(r)
  File "/home/b1oki/.virtualenvs/myvirtualenv/lib/python3.10/site-packages/telepot/api.py", line 147, in _parse
    raise e(description, error_code, data)
telepot.exception.BotWasBlockedError: ('Forbidden: bot was blocked by the user', 403, {'ok': False, 'error_code': 403, 'description': 'Forbidden: bot was blocked by the user'})
```

**Comment by b1oki** [comment]
Добавил обработку `telepot.exception.BotWasBlockedError`
